"""gen_roadmap.py -- builds IDEA_ROADMAP.md from results/stage14_*.csv (tables are generated)."""
import os
import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
R = lambda f, **k: pd.read_csv(os.path.join(HERE, 'results', f), **k)
core = R('stage14_core.csv', index_col=0)
bt = R('stage14_bootstrap.csv', index_col=0)
pm = R('stage14_portfolio_marginal.csv')
cost = R('stage14_cost_sensitivity.csv')
cap = R('stage14_capacity_recent.csv', index_col=0)
tf = R('stage14_trendfilter_check.csv')
steps = R('stage14_final_blend_steps.csv')
plan = R('stage14_planning_ranges.csv', index_col=0)
brk = R('stage14_breakout_sim.csv')
brk_cost = R('stage14_breakout_cost.csv')
vixo = R('stage14_vix_override.csv')

_log = pd.read_csv(os.path.join(HERE, '..', 'gold_sleeve', 'output', 'gold_sleeve_monthly_log.csv'), index_col=0, parse_dates=True)
def _st(r):
    r = r.dropna(); eq = (1 + r).cumprod(); y = len(r) / 12
    return dict(cagr=eq.iloc[-1] ** (1 / y) - 1, vol=r.std() * 12 ** 0.5, sharpe=((r - (1.06 ** (1 / 12) - 1)).mean() / r.std()) * 12 ** 0.5, maxdd=(eq / eq.cummax() - 1).min())
_pvf, _pvh = _st(_log['net_return']), _st(_log.loc[_log.index >= '2015-01-01', 'net_return'])
_pl_lo, _pl_hi = 0.5 * _pvh['sharpe'], 0.8 * _pvh['sharpe']
_cg = lambda sh: 0.06 + sh * _pvh['vol'] - _pvh['vol'] ** 2 / 2
PV = dict(full=_pvf, hold=_pvh, sh_lo=_pl_lo, sh_hi=_pl_hi, cg_lo=_cg(_pl_lo), cg_hi=_cg(_pl_hi), dd_lo=_pvf['maxdd'] * 1.25, dd_hi=_pvf['maxdd'] * 1.5)
_gm = pd.read_csv(os.path.join(HERE, 'results', 'stage14_portfolio_marginal.csv'))
GM = _gm[(_gm.idea == 'Gold buy&hold') & (_gm.w == 0.2)].iloc[0]
pct = lambda x, d=1: '–' if pd.isna(x) else f'{x*100:.{d}f}%'
num = lambda x, d=2: '–' if pd.isna(x) else f'{x:.{d}f}'
sgn = lambda x, d=2: '–' if pd.isna(x) else f'{x:+.{d}f}'


def md(rows, header):
    out = ['| ' + ' | '.join(header) + ' |', '|' + '|'.join(['---'] * len(header)) + '|']
    out += ['| ' + ' | '.join(str(c) for c in r) + ' |' for r in rows]
    return '\n'.join(out)


L = []
A = L.append
A('# Idea roadmap — what to build, in what order, and what to expect')
A('')
A('_Decision document built on `NEW_STRATEGY_IDEAS.md`. Every number comes from `results/stage14_*.csv` (scripts `stage14*_*.py`, tables generated by `gen_roadmap.py`)._')
A('> **Data correction (2026-10-06).** While building the gold strategy I found that every ETF file downloaded in two chunks — all gold ETFs, JUNIORBEES and LIQUIDBEES — is **missing 2011-01 → 2014-12**. The earlier version of this roadmap forward-filled gold across that gap (47 months showed exactly 0% and one month +22%). '
  'All gold figures below are recomputed with the gap treated as missing. Effect: gold buy-and-hold CAGR 13.4% → 15.8%, Sharpe 0.54 → 0.66, correlation to the bucket −0.19 → −0.23, ΔSharpe at 20% weight +0.13 → +0.16; the blend\'s Sharpe gain moved from +0.24 to +0.22. '
  'The −17% gold drawdown is now a **floor** (the unobserved four years could hide a larger one). The X1 asset-rotation numbers still contain the gap-filled gold leg and were not re-run (the idea stays cut: even that version is dominated by gold alone).')
A('')
A('> **Superseded for gold (2026-10-06, real engines).** The gold evidence below was measured on my simplified proxy books (Sharpe ≈ 0.7). Re-tested on your actual Elendel / Zenith / Quad engines (Sharpe 1.7–1.9, `momentum_gold/`), gold is much less valuable: the literal idea of moving all idle cash to gold in weak markets **lowers** Sharpe by 0.09–0.17 and deepens drawdowns 5–11 pts; a 10%-capped weak-market overlay adds only about +0.6 CAGR pt / +0.03 Sharpe with unchanged drawdown (≈ 0 if gold\'s drift disappears); and a static 10% sleeve\'s gain vanishes when gold\'s drift is neutralised. '
  'The larger, riskless lever is sweeping idle cash into a liquid fund (+2.8 to +3.1 pts CAGR for Elendel/Quad backtests that assume 0%). Treat the "BUILD #1 gold" ranking below as **downgraded to optional / small**.')
A('')

# ------------------------------------------------------------------ section 1
A('## 1. Decision')
A('')
A('Of the ~20 candidates (counting variants), **two clear builds (gold sleeve, I1), one conditional build (I6 breakout), one optional sleeve (I3), one cheap test, one tweak to something you already run — and the rest are cut.** Order (best evidence and lowest effort first):')
A('')
pl = plan
A(md([
    ['**1** (built)', '**Gold sleeve** — `gold_sleeve/` (standalone) and `momentum_gold/` (capped idle-cash overlay, the form the real-engine tests support) — **downgraded, see note above**', f'Decorrelated stream on my proxy books (corr {GM.corr_to_bucket:+.2f} to your books). No gold timing edge exists in the data (best signal t=1.1), so the sleeve is built as a **risk tool**: at equal risk it matches buy-and-hold Sharpe and cuts the blended drawdown ~2-3 pts.',
     f'CAGR {pct(PV["cg_lo"],0)}–{pct(PV["cg_hi"],0)}, Sharpe {num(PV["sh_lo"])}–{num(PV["sh_hi"])} standalone; max DD {pct(PV["full"]["maxdd"],0)} backtest (a floor) → plan {pct(PV["dd_lo"],0)} to {pct(PV["dd_hi"],0)}', 'done (strategy + backtest + parity test)'],
    ['**2**', '**I1 Tight-range trend** — `tight_close_15` + `q5_126`, rank 301–1000, on the Elendel chassis',
     'The only stock idea that clearly beats the control: P=0.99 over the full sample, but only 0.73 for 2015+ alone (weaker evidence), and it still leads on the live-style SMA200-filtered chassis (2015+ Sharpe 0.82 vs 0.74). Pure factor swap in `csm_elendel_strategy.py`. Capacity is the catch (≈₹9.5 cr).',
     f'Sharpe {num(pl.iloc[0].plan_sharpe_lo)}–{num(pl.iloc[0].plan_sharpe_hi)}, CAGR {pct(pl.iloc[0].plan_cagr_lo,0)}–{pct(pl.iloc[0].plan_cagr_hi,0)}, max DD {pct(pl.iloc[0].plan_dd_lo,0)} to {pct(pl.iloc[0].plan_dd_hi,0)}', 'low (factor swap)'],
    ['**3** (conditional)', '**I6 Breakout v3** — 52w-high breakout, RS top-25% + Stage-2 template, no volume rule, 20 slots, −10% stop / −20% trail',
     'Profitable in all 18 pre-set exit/gate/signal variants (Sharpe 0.74–1.13) with a different shape (39% win rate, ~5.8× payoff). **Conditional** because it narrowly misses rule 2: 2015+ Sharpe ties the control (0.74 vs 0.75, P=0.50). Prototype only.',
     f'Sharpe {num(pl.iloc[1].plan_sharpe_lo)}–{num(pl.iloc[1].plan_sharpe_hi)}, CAGR {pct(pl.iloc[1].plan_cagr_lo,0)}–{pct(pl.iloc[1].plan_cagr_hi,0)}, max DD {pct(pl.iloc[1].plan_dd_lo,0)} to {pct(pl.iloc[1].plan_dd_hi,0)}', 'medium (event chassis exists)'],
    ['optional', '**I3 Low-risk sleeve** — `lowvol_126` + `low_ulcer_252`, top-250, **no** SMA200 universe filter',
     'Diversifier: corr 0.51, adds +0.05 Sharpe and cuts the bucket\'s drawdown 3.5 pts, but **misses rule 3** (Sharpe at 2.5× cost 0.69 < control 0.76) and **breaks under the live SMA200 universe filter** (2015+ Sharpe 0.56 → 0.28). Gold already provides most of the diversification — add this only if you want more drawdown protection.',
     f'Sharpe {num(pl.iloc[2].plan_sharpe_lo)}–{num(pl.iloc[2].plan_sharpe_hi)}, CAGR {pct(pl.iloc[2].plan_cagr_lo,0)}–{pct(pl.iloc[2].plan_cagr_hi,0)}', 'low (factor swap, different filter)'],
    ['test', '**Vol-target overlay** (20% target, lagged) on existing books', 'Cut max DD from −58…−74% to −37…−41% in stripped books; marginal value on live books (which already have regime leverage/Crash Guard) is unknown.', 'measure in live engine first', 'low'],
    ['merge', 'I2 residual+persistence', 'ΔSharpe +0.05 to the bucket (P=0.96) but fails the live-style filter test (−0.08 vs control) and it is essentially your residual-momentum book. Not a new strategy.', '–', '–'],
], ['#', 'Idea', 'Why', 'Planning expectation (net of costs, see §6)', 'Effort']))
A('')
A('**What the builds do together** (equal-weight blend of your four live-like momentum books + 10% gold + 15% I1 + 10% low-risk + 10% breakout; weights fixed in advance, not optimised). The last row drops the optional I3 sleeve:')
A('')
rows = []
for _, r in steps.iterrows():
    rows.append([r.step, pct(r.cagr), pct(r.vol), num(r.sharpe), pct(r.maxdd), num(r.calmar), num(r.sharpe_hold), pct(r.maxdd_hold)])
import pickle
from portfolio_lab import stats as _stats
_fin = pickle.load(open(os.path.join(HERE, '.cache', 'stage14_final.pkl'), 'rb'))
_D, _B = _fin['D'], _fin['B']
_alt = 0.65 * _B + 0.10 * _D['Gold buy&hold'] + 0.15 * _D['I1 tight+persist (mid/small, live-style filter)'] + 0.10 * _D['I6 breakout (RS25+TT, sim)']
_a, _h = _stats(_alt), _stats(_alt[_alt.index > '2014-12-31'])
rows.append(['Alternative without I3: 65% bucket + 10% gold + 15% I1 + 10% breakout', pct(_a['cagr']), pct(_a['vol']), num(_a['sharpe']), pct(_a['maxdd']), num(_a['calmar']), num(_h['sharpe']), pct(_h['maxdd'])])
A(md(rows, ['Step (cumulative)', 'CAGR', 'Vol', 'Sharpe', 'Max DD', 'Calmar', 'Sharpe 2015+', 'Max DD 2015+']))
A('')
b0, b1 = steps.iloc[0], steps.iloc[-1]
A(f'**Honest reading:** the blend improves Sharpe by {b1.sharpe-b0.sharpe:+.2f} (block-bootstrap 90% interval +0.13 to +0.33) and the worst drawdown by about {abs(b1.maxdd-b0.maxdd)*100:.0f} points, '
  f'but **CAGR only moves {pct(b0.cagr)} → {pct(b1.cagr)}**. What you get is a smoother ride (vol {pct(b0.vol)} → {pct(b1.vol)}), not materially more return. '
  f'Planning for live use, take roughly **half to four-fifths** of the improvement: Sharpe +0.09 to +0.14 and a drawdown improvement of roughly 3–6 points.')
A('')

# ------------------------------------------------------------------ section 2
A('## 2. How the cut was made')
A('')
A('**Common chassis.** Every stock idea was run as a monthly top-15 equal-weight book, 0.3% one-way costs, then the *same* overlay: SMA200 market gate (50% exposure in bear), 20% volatility target (6-month trailing book vol, lagged one month), and cost on exposure changes. '
  'Control = the Elendel signal (`a3_rs_high` + `q5_126`) run through that identical chassis. This removes the "stripped book vs live book" apples-to-oranges problem within the comparison, though not versus your live engine.')
A('')
A('**"Live-like bucket"** = equal-weight blend of four books on that chassis (Elendel, Zenith, csm_absolute score, residual momentum). It is a proxy for your 5–6 live momentum strategies, not the real thing; the true marginal value of any idea will differ.')
A('')
A('**Rubric** (written after the exploratory study and before the stress tests were run; it is a decision rule, not a result). BUILD requires all of:')
A('')
A('1. **Adds to the bucket:** ΔSharpe ≥ +0.05 with block-bootstrap P(Δ>0) ≥ 0.95 at a 20% weight — *or* ΔMax DD ≥ 3 points with ΔSharpe ≥ 0 (diversifier).')
A('2. **Holds since 2015:** standalone 2015+ Sharpe ≥ the control\'s, *or* correlation to the bucket < 0.6.')
A('3. **Survives 2.5× costs:** Sharpe at 0.75% one-way ≥ the control\'s Sharpe at 0.30%.')
A('4. **Tradable:** a position of AUM/15 (or /20) is within 5% of average daily traded value for at least the median pick at ₹10 cr.')
A('5. **Survives the live chassis:** still beats the control when the SMA200 universe filter used by `csm_elendel_strategy.py` is applied (where that chassis is intended).')
A('')

# ------------------------------------------------------------------ section 3
A('## 3. Rule-by-rule check of the four candidates')
A('')
A('✓ = passes, ≈ = within rounding of the bar, ✗ = fails, – = not applicable. Numbers are in the scorecard below.')
A('')
A(md([
    ['Gold sleeve', f'✓ ΔSharpe {GM.d_sharpe:+.2f}, MaxDD {GM.d_maxdd*100:+.1f} pt (20% weight, buy&hold gold)', f'✓ corr {GM.corr_to_bucket:+.2f}', '–', '✓ ₹238 cr/day instrument', '–', '**BUILD** (built)'],
    ['I1 tight+persist (mid/small)', '✓ +0.11 (P=1.00)', '✓ 2015+ 0.85 vs 0.75 (live-style 0.82 vs 0.74)', '✓ 0.93 at 0.75% cost', '≈ ₹9.5 cr vs ₹10 cr bar', '✓ still beats control with SMA200 filter', '**BUILD** (watch capacity)'],
    ['I6 breakout (prototype)', '✓ +0.07 (P=1.00)', '≈ 2015+ 0.74 vs 0.75, P(beats)=0.50 — a tie, corr 0.75', '✓ 0.83 at 1.0% cost', '≈ 33% of entries >5% ADV at ₹10 cr', '–', '**CONDITIONAL**'],
    ['I3 low-risk (top-250)', '✓ +0.05 (P=0.97), MaxDD +3.5 pt', '✓ corr 0.51', '✗ 0.69 at 0.75% cost < control 0.76', '✓ ≈ ₹100+ cr', '✗ 2015+ Sharpe 0.28 with filter (spec removes it)', '**OPTIONAL**'],
], ['Candidate', '1 Adds to bucket', '2 Holds since 2015', '3 Survives 2.5× cost', '4 Tradable at ₹10 cr', '5 Live chassis', 'Result']))
A('')
A('**One input I need from you:** the capital you expect to run per strategy. I1 is the capacity-constrained one — at roughly ₹10 cr it is on the line, above that it needs multi-day execution or accepting more slippage (the liquid-1000 version has ₹33 cr capacity but fails the live-chassis test).')
A('')
A('## 4. Scorecard')
A('')
ctrl_cost = cost[(cost.idea == 'Elendel (control)') & (cost.cost_one_way == 0.003)].sharpe.iloc[0]
def cost_sharpe(name, c=0.0075):
    d = cost[(cost.idea == name) & (cost.cost_one_way == c)]
    return d.sharpe.iloc[0] if len(d) else np.nan
def capmed(name):
    return cap.loc[name, 'AUM_cr_median_within_5%ADV'] if name in cap.index else np.nan

order = [
    ('Elendel (control)', 'control', None),
    ('I1 tight+persist (mid/small)', 'BUILD #2', None),
    ('I1 tight+persist (liquid)', 'cut', 'dominated by mid/small; fails live-filter test (−0.02 holdout vs control)'),
    ('I6 breakout sim (52w-high+RS25+TT, stop10/trail20, gate)', 'BUILD #3 (conditional)', 'narrowly misses rule 2 (ties control since 2015)'),
    ('Gold buy&hold', 'BUILD #1', None),
    ('I3 low-risk (top250)', 'OPTIONAL', 'misses rule 3 (cost) and rule 5 (live filter)'),
    ('I3 low-risk (liquid)', 'cut', 'ΔSharpe +0.02 only'),
    ('I2 resid+persist (liquid)', 'merge', 'ΔSharpe +0.047 (P=0.96): just under the +0.05 bar; ≈ residual-momentum book'),
    ('I2 resid+persist (top250)', 'cut', 'ΔSharpe +0.03; −0.08 vs control on live chassis'),
    ('I0 persistence only (q5_126)', 'cut', 'holdout Sharpe −0.11 vs control (P=0.19)'),
    ('I4 intraday+ulcer (top250)', 'cut', 'ΔSharpe +0.02 (P=0.75); −0.25 holdout vs control on live chassis'),
    ('I7 anchor+pain (liquid)', 'cut', 'no portfolio gain; holdout Sharpe 0.27'),
    ('X1 asset rotation (ensemble of 24 configs)', 'cut', 'all of its value is the gold leg (+0.005 ΔSharpe; dominated by gold alone)'),
    ('X4 sector rotation (ensemble of 18 configs)', 'cut', 'Sharpe 0.43, ΔSharpe −0.05, DD worse than gold'),
    ('Zenith', 'live', None), ('csm_absolute score', 'live', None), ('Residual mom (live-like)', 'live', None),
]
rows = []
mp = pm[pm.w == 0.2].set_index('idea')
for nm, verdict, why in order:
    cn = nm
    c = core.loc[cn] if cn in core.index else (core.loc['I6 breakout sim (52w-high+RS25+TT, stop10/trail20, gate)'] if False else None)
    if nm.startswith('I6 breakout'):
        # not in stage14_core (appended later) -> use bootstrap/marginal files and the planning table
        c = None
    b = bt.loc[nm] if nm in bt.index else None
    m = mp.loc[nm] if nm in mp.index else None
    if nm.startswith('I6 breakout') :
        bsim = 'I6 breakout sim (52w-high+RS25+TT, stop10/trail20, gate)'
        r_ = plan.loc['I6 breakout (RS25+TT, sim)']
        cagr, sh, dd, shh = r_.cagr_full, r_.sharpe_full, r_.maxdd_full, r_.sharpe_hold
    else:
        cagr, sh, dd, shh = (c.cagr, c.sharpe, c.maxdd, c.sharpe_hold) if c is not None else (np.nan,) * 4
    rows.append([nm.replace(' (52w-high+RS25+TT, stop10/trail20, gate)', ' (52w-high+RS25+TT)'), f'{pct(cagr)} / {num(sh)} / {pct(dd,0)}', num(shh),
                 '–' if b is None else f'{num(b.p_beats_ctrl)} / {num(b.p_beats_ctrl_hold)}', '–' if b is None else num(b.corr_ctrl),
                 '–' if m is None else f'{sgn(m.d_sharpe)} ({num(m.p_sharpe_up)}) / {sgn(m.d_maxdd*100,1)}pt',
                 num(cost_sharpe(nm)), '–' if np.isnan(capmed(nm)) else f'₹{capmed(nm):.0f} cr', f'**{verdict}**' + (f' — {why}' if why else '')])
A(md(rows, ['Idea', 'CAGR / Sharpe / MaxDD (full, chassis)', 'Sharpe 2015+', 'P(beats control) full / 2015+', 'Corr to control', 'Δ bucket Sharpe (P>0) / ΔMaxDD @20%', 'Sharpe @0.75% cost', 'Capacity (₹ cr)¹', 'Verdict']))
A('')
A(f'_Control Sharpe at 0.30% cost = {ctrl_cost:.2f}; at 0.75% = {cost_sharpe("Elendel (control)"):.2f}. ¹ Capacity = AUM at which the *median* pick (2022-07 → 2026-06) is within 5% of its 63-day median daily traded value. '
  'Breakout simulation capacity is measured at entry (₹10 cr: 33% of entries exceed 5% of ADV). "Live" rows are your existing strategy proxies, shown for reference, not candidates. '
  'Bucket baseline for the Δ columns: Sharpe 0.71, Max DD −26.7% (2008-04 → 2026-06). The blend table in §1 uses the shorter common window of all series, where the bucket Sharpe is 0.76._')
A('')
A('**Idea-level evidence that is not a portfolio test** (so it cannot pass the rubric, and is cut or parked):')
A('')
rows = [
    ['X3 VIX-spike contrarian re-entry', f'Tested as an exposure override on the bucket (2010-06+, 21 qualifying months): Sharpe {vixo.iloc[1].sharpe:.2f} vs {vixo.iloc[0].sharpe:.2f}, max DD {pct(vixo.iloc[1].maxdd)} vs {pct(vixo.iloc[0].maxdd)} — **made it worse**.', 'cut'],
    ['X5 index timing (breadth/SMA/VIX/vol)', 'Balanced accuracy 0.50–0.57, timed CAGR below buy-and-hold; the SMA200 gate is already in the chassis.', 'cut (as strategy)'],
    ['S1 1-month seasonality', 'IC 1m 0.024 (t 4.6), zero after one month, 75–85% turnover, lowered book Sharpe when added.', 'cut'],
    ['I5 csm_absolute score', 'Signal is accurate (ICIR 0.69) but it is *already live*; in this proxy its book ranks last in the bucket (P(beats control)=0.07). Not a new idea.', 'n/a (live)'],
    ['X2 factor-index regime switch', 'Low-vol index beats Nifty 500 by +1.6%/month when the market is >10% off its high (59% hit) — real but small; superseded by the gate + low-risk sleeve.', 'park'],
]
A(md(rows, ['Idea', 'Evidence', 'Verdict']))
A('')

# ------------------------------------------------------------------ section 4
A('## 5. Build specifications, evidence and kill criteria')
A('')
A('Kill criteria are what the full event-driven engine (your stops, Crash Guard, hysteresis, real costs) must show before capital is committed. They are set deliberately below the backtest numbers so that a pass is meaningful but not a coin flip.')
A('')

I1 = plan.loc['I1 tight+persist (mid/small, live-style filter)']
A('### Build 1 — Gold sleeve  (implemented in `gold_sleeve/`)')
A('')
A('* **Spec:** `GoldSleevePV` — exposure = persistence × volatility scale, decided at month-end, traded next close: persistence = share of the last 126 days gold closed above its 50-day SMA; volatility scale = min(1, 12% / 63-day annualised vol); remainder in cash/liquid fund. Instrument GOLDBEES (₹238 cr median daily value). `mode="buy_hold"` is built in for A/B. Parity-tested against the research series (exact), gap-safe, with a stale-data guard for live use.')
A(f'* **Why this logic:** gold timing has **no demonstrable return edge** here — the best time-series signal (12-month momentum) has a t-stat of 1.1 and classic TSMOM/SMA rules did not beat buy-and-hold as a sleeve. The persistence × volatility rule is chosen for what a sleeve is for: at an equal risk budget to a 10% buy-and-hold sleeve (≈19% weight) the blended max drawdown was shallower in 81/81 neighbouring parameter sets (+1.4 to +3.5 pts) with unchanged Sharpe, and the real exposure path beat 86–90% of time-shifted placebo paths on drawdown.')
A(f'* **Evidence (usable months only, gap excluded):** standalone sleeve CAGR {pct(PV["full"]["cagr"])}, vol {pct(PV["full"]["vol"])}, Sharpe {num(PV["full"]["sharpe"])}, max DD {pct(PV["full"]["maxdd"])}; since 2015: CAGR {pct(PV["hold"]["cagr"])}, Sharpe {num(PV["hold"]["sharpe"])}. Buy-and-hold gold on the same months: CAGR {pct(core.loc["Gold buy&hold","cagr"])}, max DD {pct(core.loc["Gold buy&hold","maxdd"])}. Buy-and-hold gold at 20% of the bucket: ΔSharpe {GM.d_sharpe:+.2f} (P={GM.p_sharpe_up:.2f}), max DD {pct(GM.base_maxdd)} → {pct(GM.new_maxdd)}; correlation with the bucket **{GM.corr_to_bucket:+.2f}**.')
A(f'* **Expectation:** planning CAGR {pct(PV["cg_lo"],0)}–{pct(PV["cg_hi"],0)} and max DD {pct(PV["dd_lo"],0)} to {pct(PV["dd_hi"],0)} standalone (a floor: the unobserved 2011–14 years and single-day gold gaps like January 2026\'s −10% are not in the drawdown). It gives up about 4–5 CAGR points versus holding gold (it averages ~52% exposure) in exchange for a drawdown about 10 points shallower. Do not expect a return boost; 2008–2026 was a strong INR gold period.')
A('* **Risk:** monthly decisions only — no intra-month stop; gold can gap (−10% in one day on 2026-01-30). The rule de-risked from 96% (Aug 2025) to ~24% (Jul 2026) as volatility rose. Taxes on frequent rebalancing are not modelled.')
A('* **Kill/Review:** drop the timing logic and hold gold statically (or revisit sizing) if (i) the live sleeve\'s drawdown is not clearly shallower than buy-and-hold over a full gold drawdown, or (ii) the rolling 3-year correlation of gold with the equity bucket rises above +0.3.')
A('')
A('### Build 2 — I1 Tight-range trend')
A('')
A('* **Spec:** copy `csm_elendel_strategy.py`; replace the factor pair with `tight_close_15` (= −std(close, 15d) / mean(close, 15d)) and `q5_126`, z-scored and summed; set `universe_top_n_min=301`, `universe_top_n_max=1000`; keep SMA200 filter, absolute-momentum gate, top-15 with hysteresis/swap-gap, inverse-vol sizing, Crash Guard. '
  'In the proxy the overlay was an SMA200 market gate + 20% vol target.')
A(f'* **Evidence (live-style chassis, with SMA200 universe filter):** full-sample CAGR {pct(I1.cagr_full)}, Sharpe {num(I1.sharpe_full)}, max DD {pct(I1.maxdd_full)}; since 2015 CAGR {pct(I1.cagr_hold)}, Sharpe {num(I1.sharpe_hold)}, max DD {pct(I1.maxdd_hold)} versus the control\'s 2015+ Sharpe 0.74. ΔSharpe vs control +0.28 full / +0.07 since 2015. '
  'Adds +0.11 Sharpe to the bucket (P=1.00) at a 20% weight for the unfiltered version, and +0.09 at a 15% weight for the live-style version (blend table, §1). Mid/small IC is strong (ICIR 0.92, t 11) and the tightness leg is nearly uncorrelated with Elendel (corr ≈ 0). '
  f'**But most of the full-sample lead is from 2004–2014:** since 2015 the edge over the Elendel control is only about {(core.loc["I1 tight+persist (mid/small)","cagr_hold"]-core.loc["Elendel (control)","cagr_hold"])*100:+.1f} CAGR points and {core.loc["I1 tight+persist (mid/small)","sharpe_hold"]-core.loc["Elendel (control)","sharpe_hold"]:+.2f} Sharpe (unfiltered chassis).')
A(f'* **Expectation:** plan for **Sharpe {num(I1.plan_sharpe_lo)}–{num(I1.plan_sharpe_hi)}, CAGR {pct(I1.plan_cagr_lo,0)}–{pct(I1.plan_cagr_hi,0)}, max DD {pct(I1.plan_dd_lo,0)} to {pct(I1.plan_dd_hi,0)}** — i.e. mid-teens, not the 33% full-sample backtest (which is dominated by 2004–2014). '
  'Cost-robust: Sharpe 1.21 / 1.09 / 0.93 / 0.78 at 0.3 / 0.5 / 0.75 / 1.0% one-way.')
A('* **Risks:** turnover ≈ 0.65 of the book per month in the proxy (hysteresis should cut it); mid/small capacity ≈ ₹10 cr at ≤5% of ADV per position (about half of Elendel\'s); tight closes can reflect thin trading; correlation with Elendel book 0.81–0.88, so it is a *better* momentum book, not a different return stream.')
A('* **Kill criteria (full engine):** 2015+ Sharpe ≥ 0.55 **and** ≥ the same-engine Elendel + 0.05; max DD ≤ 35%; monthly turnover ≤ 0.8. Ablation: if `q5_126` alone on the same universe gives ≥ the same Sharpe, drop the tightness leg.')
A('')
A('### Build 3 (conditional) — I6 Breakout v3')
A('')
A('* **Spec:** liquid-1000 universe; signal = close above prior 252-day closing high and no such breakout in the previous 10 days; require top-quartile 6-month (lag 1-month) return rank and the Stage-2 template (C>SMA50>SMA150>SMA200, SMA200 rising, within 25% of 52w high, >30% above 52w low); **no volume rule**; enter next close; 20 slots, each 1/20 of equity; rank by RS when more signals than slots; exit next close after a close ≤ entry −10% or ≤ peak −20%; no new entries while the equal-weight index is below its SMA200.')
sel = brk[(brk.signal == '52w-high + RS25 + TT') & (brk.stop == 0.10) & (brk.gate == True)].iloc[0]
allv = brk[brk.signal.str.contains('RS25')]
A(f'* **Evidence (prototype, 0.3% one-way, idle cash 6%):** CAGR {pct(sel.cagr)}, Sharpe {num(sel.sharpe)}, max DD {pct(sel.maxdd)}; since 2015 CAGR {pct(sel.cagr_hold)}, Sharpe {num(sel.sharpe_hold)}; {int(sel.trades)} trades, win rate {pct(sel.win_rate,0)}, average win {pct(sel.avg_win,0)} vs average loss {pct(sel.avg_loss,0)} (payoff {sel.payoff:.1f}×). '
  f'Across the 12 pre-set exit/gate variants of the two RS-gated signals, Sharpe ranges {allv.sharpe.min():.2f}–{allv.sharpe.max():.2f}; none were tuned. At 1.0% one-way costs Sharpe is {brk_cost.iloc[2].sharpe:.2f} (2015+ {brk_cost.iloc[2].sharpe_hold:.2f}).')
A(f'* **Expectation:** plan for **Sharpe {num(plan.loc["I6 breakout (RS25+TT, sim)","plan_sharpe_lo"])}–{num(plan.loc["I6 breakout (RS25+TT, sim)","plan_sharpe_hi"])}, CAGR {pct(plan.loc["I6 breakout (RS25+TT, sim)","plan_cagr_lo"],0)}–{pct(plan.loc["I6 breakout (RS25+TT, sim)","plan_cagr_hi"],0)}, max DD {pct(plan.loc["I6 breakout (RS25+TT, sim)","plan_dd_lo"],0)} to {pct(plan.loc["I6 breakout (RS25+TT, sim)","plan_dd_hi"],0)}** and a **~60% losing-trade rate** — you must be able to tolerate that. Adds +0.07 Sharpe to the bucket (P=0.997); correlation with the bucket 0.79.')
A('* **Risks:** the prototype ignores circuit-limit fills, gap-through-stop and per-name ADV limits (33% of entries exceed 5% of ADV at ₹10 cr); event-study evidence shows the edge is momentum/RS in disguise, so correlation to your momentum books is high; ungated 52w-high breakouts did about as well in the prototype once slots are ranked by RS, so the RS **ranking** (not the gate) is what carries it.')
A('* **Kill criteria (HR/VCP chassis):** 2015+ Sharpe ≥ 0.55; win rate 33–45% and payoff ≥ 4×; Sharpe range across the three stop settings (8/15, 10/20, 12/25) ≤ 0.4 (else fragile).')
A('')
A('### Optional — I3 Low-risk sleeve')
A('')
A('* **Spec:** factors `lowvol_126` (−std of daily returns, 126d) + `low_ulcer_252` (−RMS drawdown from trailing 252d peak), top-250 liquidity universe, top-15, **no SMA200 universe filter** and no absolute-momentum gate (neither was in the tested book); keep the market gate/Crash Guard.')
I3p = plan.loc['I3 low-risk (top250, no trend filter)']
A(f'* **Evidence:** full-sample CAGR {pct(I3p.cagr_full)}, Sharpe {num(I3p.sharpe_full)}, max DD {pct(I3p.maxdd_full)}; since 2015 CAGR {pct(I3p.cagr_hold)}, Sharpe {num(I3p.sharpe_hold)}, max DD {pct(I3p.maxdd_hold)}. With the live SMA200 universe filter it falls to a 2015+ Sharpe of 0.28 (CAGR 8.9%). In the bucket at 20%: ΔSharpe +0.05 (P=0.97), max DD −3.5 pts, correlation 0.51.')
A(f'* **Expectation:** plan for Sharpe {num(I3p.plan_sharpe_lo)}–{num(I3p.plan_sharpe_hi)}, CAGR {pct(I3p.plan_cagr_lo,0)}–{pct(I3p.plan_cagr_hi,0)}. It is a risk-reduction sleeve; **do not expect it to earn its keep as a return source**. Capacity is the best of the four (≈ ₹95 cr).')
A('* **Kill criteria:** 2015+ Sharpe ≥ 0.4 in the full engine and correlation to the bucket ≤ 0.65; otherwise drop (gold already provides most of the diversification).')
A('')
A('### Test — Vol-target overlay')
A('')
A('Apply a 20% annualised volatility target (exposure = min(1, 20% / trailing-6-month book vol), lagged one month) to existing live books *in the backtest engine* and compare max DD and Sharpe with and without. Stripped-book evidence: Elendel DD −66.8% → −44.4%, residual+persistence −68.6% → −44.6%, with a 0–5-point CAGR cost; combined with the SMA200 gate −41%/−37%. Treat as unproven until measured against your real books.')
A('')

# ------------------------------------------------------------------ section 5
A('## 6. How to read the "planning expectation"')
A('')
A('The backtests are optimistic in ways that cannot all be measured, so each build idea carries an explicit haircut. **This is judgment, not a statistical estimate.**')
A('')
A('* **Sharpe:** 50%–80% of the idea\'s **2015+** Sharpe (the more recent and less-flattering period; the same idea earned much more in 2004–2014).')
A('* **CAGR:** 6% (cash) + Sharpe × 2015+ volatility − volatility²/2.')
A('* **Max drawdown:** the full-sample worst drawdown × 1.25–1.5 (the sample contains 2008 and 2020 but not every possible path).')
A('* **Portfolio improvement:** 50%–80% of the measured 2015+ improvement.')
A('* **Why the haircut:** (i) survivorship — only ~2% of symbols are delisted (removing the known delisted names changed results by <0.02 Sharpe, so the bias comes from names missing entirely and cannot be measured here); (ii) the factor pairs were chosen after seeing single-factor results; '
  '(iii) 2015+ decay — price-based IC was 30–40% lower after 2014; (iv) the proxy ignores execution frictions (circuit limits, partial fills).')
A('')
rows = []
for nm in plan.index:
    r = plan.loc[nm]
    rows.append([nm, f'{pct(r.cagr_full)} / {num(r.sharpe_full)} / {pct(r.maxdd_full,0)}', f'{pct(r.cagr_hold)} / {num(r.sharpe_hold)} / {pct(r.maxdd_hold,0)}',
                 f'{num(r.plan_sharpe_lo)}–{num(r.plan_sharpe_hi)}', f'{pct(r.plan_cagr_lo,0)}–{pct(r.plan_cagr_hi,0)}', f'{pct(r.plan_dd_lo,0)} to {pct(r.plan_dd_hi,0)}'])
rows.insert(3, ['Gold sleeve (persistence × vol, built)', f'{pct(PV["full"]["cagr"])} / {num(PV["full"]["sharpe"])} / {pct(PV["full"]["maxdd"],0)}', f'{pct(PV["hold"]["cagr"])} / {num(PV["hold"]["sharpe"])} / –', f'{num(PV["sh_lo"])}–{num(PV["sh_hi"])}', f'{pct(PV["cg_lo"],0)}–{pct(PV["cg_hi"],0)}', f'{pct(PV["dd_lo"],0)} to {pct(PV["dd_hi"],0)}'])
A(md(rows, ['Idea', 'Backtest full: CAGR / Sharpe / MaxDD', 'Backtest 2015+: CAGR / Sharpe / MaxDD', 'Planning Sharpe', 'Planning CAGR', 'Planning max DD']))
A('')
A('"Live-like bucket" is shown for scale: the same haircut applied to your own books gives Sharpe 0.28–0.45 / CAGR 10–13% — so the planning numbers for the new ideas are conservative *relative to a baseline treated the same way*, and what matters for the decision is the **difference** to the bucket, not the absolute levels.')
A('')

# ------------------------------------------------------------------ section 6
A('## 7. What was cut and why')
A('')
cut_rows = [
    ['I0 persistence only (`q5_126`)', 'Simplifying Elendel to one leg: holdout Sharpe −0.11 vs control (P=0.19). Not robust.'],
    ['I1 liquid-1000 version', 'Dominated by the mid/small version; fails the live-chassis filter test (2015+ ΔSharpe −0.02).'],
    ['I2 residual + persistence', 'ΔSharpe +0.047 (P=0.96) sits just under the bar and it is −0.08 vs control on the live chassis (top-250). It overlaps your residual-momentum strategy; try it only as a signal tweak there.'],
    ['I3 liquid-1000 version', 'ΔSharpe +0.02; the top-250 version is better.'],
    ['I4 intraday + ulcer (top-250)', 'ΔSharpe +0.02 (P=0.75); under the live filter holdout Sharpe 0.45 vs control 0.74. The intraday-vs-overnight finding is real at factor level (t≈5) but has not translated into a book that beats the control.'],
    ['I7 anchor + pain', 'IC looks great, book does not: 2015+ Sharpe 0.27, no portfolio gain. The clearest case of IC not being enough.'],
    ['X1 asset-class rotation', 'Ensemble of 24 configurations (computed with the gap-filled gold leg; not re-run): Sharpe 0.54 vs gold alone 0.66 on corrected data. Marginal Sharpe +0.005 vs +0.16 for gold alone. The rotation logic adds nothing over holding the gold leg.'],
    ['X4 sector rotation', 'Ensemble Sharpe 0.43, ΔSharpe −0.05, drawdown −48%. No.'],
    ['X3 VIX-spike re-entry', 'Tested as an overlay: worse (Sharpe −0.03, max DD −4 pts) over 21 qualifying months. The factor-level signal does not survive being traded.'],
    ['X5 index timing', 'Accuracy 0.50–0.57; reduces drawdown but costs CAGR; the market gate already sits in the chassis.'],
    ['S1 seasonality', 'One-month effect only; costly turnover; no portfolio gain.'],
    ['Single factors tested and rejected', 'Reversal, illiquidity/size, volume spikes, gap-chasing, high beta, ATR/range expansion, jump frequency, regime-switched beta, sector-momentum level, high-volatility seeking (negative IC).'],
]
A(md(cut_rows, ['Idea', 'Reason']))
A('')

# ------------------------------------------------------------------ section 7
A('## 8. Implementation sequence')
A('')
A('1. **Gold sleeve** — allocation change, no engine work; decide weight (10%) and cap.')
A('2. **I1 in the Elendel chassis** — new strategy file from `csm_elendel_strategy.py` with the factor swap and `universe_top_n_min=301`; backtest in `run_csm_elendel_backtest.py` style; compare against Elendel *in the same run*; check the kill criteria in §5.')
A('3. **Vol-target overlay test** on existing books (cheap; informs the sizing for steps 2 and 4).')
A('4. **I6 breakout v3** in the HR/VCP event chassis with the spec in §5; include the 8/15, 10/20, 12/25 stop sweep as a fragility check. Conditional: proceed only if the full-engine 2015+ Sharpe clears the kill criteria.')
A('5. **I3 low-risk sleeve** only if gold alone does not give enough drawdown protection (it misses two of the five rules).')
A('6. For every build: 3–6 months of paper trading, tracking realised vs modelled costs and turnover, before real capital.')
A('')

# ------------------------------------------------------------------ section 8
A('## 9. Caveats (what these numbers cannot tell you)')
A('')
A('* **Proxy, not your engine.** The "bucket" and the control are simplified books on a shared chassis. Your live strategies have their own stops, hysteresis and regime logic, so absolute levels and marginal gains will differ; only the *ranking* of ideas should be trusted at this stage.')
A('* **Survivorship** is unquantified and flatters every long-only price signal (low-risk and smooth-trend screens most).')
A('* **Selection effects:** the four builds were chosen from ~20 ideas, the pairs were formed after single-factor results, and the blend weights (10/15/10/10) were fixed by hand, not optimised. The bootstrap intervals describe sampling noise in the history, not this selection risk.')
_bm = R('stage14_breakout_monthly_aligned.csv', index_col=0, parse_dates=True).iloc[:, 0]
from portfolio_lab import stats as _st2
_bd, _bh = _st2(_bm[_bm.index <= '2014-12-31']), _st2(_bm[_bm.index > '2014-12-31'])
A(f'* **Regime dependence:** gold\'s sample was favourable (CAGR {pct(core.loc["Gold buy&hold","cagr_disc"])} before 2015, {pct(core.loc["Gold buy&hold","cagr_hold"])} since). Returns faded after 2014 for the equity ideas: tight-range trend CAGR {pct(core.loc["I1 tight+persist (mid/small)","cagr_disc"],0)} → {pct(core.loc["I1 tight+persist (mid/small)","cagr_hold"],0)}, breakout prototype {pct(_bd["cagr"],0)} → {pct(_bh["cagr"],0)}, Elendel control {pct(core.loc["Elendel (control)","cagr_disc"],0)} → {pct(core.loc["Elendel (control)","cagr_hold"],0)}.')
A('* **Breakout prototype** assumes fills at the close after the signal/stop with no circuit or liquidity effects; real slippage on stop exits in small caps can be materially worse.')
A('* **Capacity** is computed from 2022–2026 traded values; it was far lower before and can shrink in a market downturn.')
A('')
A('Files: `stage14_roadmap.py` (common chassis, series), `stage14b_analysis.py` (core/bootstrap/portfolio marginal), `stage14c_stress.py` (cost, capacity, survivorship, VIX override), `stage14d_capacity_recent.py`, `stage14e_breakout_sim.py`, `stage14f_greedy.py`, `stage14g_trendfilter.py`, `stage14h_final.py` (blend, planning ranges), `gen_roadmap.py`.')

open(os.path.join(HERE, 'IDEA_ROADMAP.md'), 'w').write('\n'.join(L) + '\n')
print('written', sum(len(x) for x in L))
