"""Generates elendel_style_report.py from Old_live_strategies/run_csm_elendel_backtest.py so event-driven strategies (PEAD) print the SAME report as the Elendel-chassis strategies:
plot_performance (5 panels + monthly heatmap), compute_drawdown_stats, print_yearly_returns (with yearly max/avg drawdown), slice_results (CAGR, Sharpe, Sortino, Calmar, avg drawdown,
daily log) and the full 'PERFORMANCE REPORT' block (portfolio metrics, win rates, trade statistics, exit/entry/regime breakdowns, turnover).  Old_live_strategies is read only."""
import os, re
LIVE = '/Users/hemantsoni/Documents/long_only_strategies/Old_live_strategies'; HERE = os.path.dirname(os.path.abspath(__file__))
r = open(os.path.join(LIVE, 'run_csm_elendel_backtest.py')).read()
def between(a, b):
    i = r.index(a); j = r.index(b, i); return r[i:j]
plot = between("def plot_performance(", "def compute_drawdown_stats(")
dd = between("def compute_drawdown_stats(", "def print_yearly_returns(")
yearly = between("def print_yearly_returns(", "# ══════════════════════════════════════════════════════════════════════════════\n# SLICE & REBASE HELPER")
sl = between("def slice_results(", "# ══════════════════════════════════════════════════════════════════════════════\n# REJECT LOG COUNTERFACTUALS")
blk = between("    # ── 8. Trade-basis metrics from the filtered log", "    # ── 10. Visualisation")
blk = "\n".join(l[4:] if l.startswith("    ") else l for l in blk.splitlines()) + "\n"
blk = blk.replace('print(f"  CSM elendel v1  —  PERFORMANCE REPORT")', 'print(f"  {LABEL}  —  PERFORMANCE REPORT")')
for name in ('plot', 'sl'):
    pass
def fix(t):
    t = t.replace("csm_elendel_{VERSION_TAG}", "{PREFIX}").replace("'CSM elendel'", "LABEL").replace("CSM elendel Momentum — Monthly Returns Heatmap (%)", "' + LABEL + ' — Monthly Returns Heatmap (%)")
    t = t.replace("label='CSM elendel'", "label=LABEL")
    return t
plot, sl = fix(plot), fix(sl)
plot = plot.replace("plt.title('' + LABEL + ' — Monthly Returns Heatmap (%)'", "plt.title(LABEL + ' — Monthly Returns Heatmap (%)'")
out = '''"""elendel_style_report.py -- GENERATED by _generate_report_style.py from run_csm_elendel_backtest.py (report layout identical to the Elendel-chassis strategies). Do not edit by hand."""
import os
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns

LABEL = 'CSM strategy'
PREFIX = 'csm_strategy'
OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'output')


def configure(label, prefix, output_dir):
    global LABEL, PREFIX, OUTPUT_DIR
    LABEL, PREFIX, OUTPUT_DIR = label, prefix, output_dir


def _out(name):
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    return os.path.join(OUTPUT_DIR, name)


''' + plot + dd + yearly + sl + '''
def print_report(results, detailed_log, report_start, end_load, BACKTEST_MODE='event_driven'):
''' + "\n".join("    " + l if l.strip() else l for l in blk.splitlines()) + "\n"
open(os.path.join(HERE, 'elendel_style_report.py'), 'w').write(out)
print('written', len(out.splitlines()), 'lines')
