"""elendel_style_report.py -- GENERATED by _generate_report_style.py from run_csm_elendel_backtest.py (report layout identical to the Elendel-chassis strategies). Do not edit by hand."""
import os
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns

LABEL = 'CSM strategy'
PREFIX = 'csm_strategy'
OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'output')


def configure(label, prefix, output_dir):
    global LABEL, PREFIX, OUTPUT_DIR
    LABEL, PREFIX, OUTPUT_DIR = label, prefix, output_dir


def _out(name):
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    return os.path.join(OUTPUT_DIR, name)


def plot_performance(results, benchmark_series=None):
    equity           = results['equity_curve']
    dd               = (equity / equity.cummax()) - 1
    executed_weights = results.get('executed_weights', None)

    fig = plt.figure(figsize=(16, 20))
    gs  = fig.add_gridspec(4, 2)

    # Panel 1: Equity Curve
    ax1 = fig.add_subplot(gs[0, :])
    ax1.plot(equity.index, equity, label=LABEL, color='#1f77b4', linewidth=1.5)
    ax1.set_yscale('log')
    if benchmark_series is not None:
        bench_rb = benchmark_series / benchmark_series.iloc[0]
        ax1.plot(bench_rb.index, bench_rb, label='Benchmark', color='gray',
                 linestyle='--', alpha=0.7)
    ax1.set_title('1. Cumulative Growth (Log Scale)', fontsize=14, fontweight='bold')
    ax1.legend(fontsize=10)
    ax1.grid(True, which='both', linestyle='--', alpha=0.3)
    ax1.set_ylabel('Portfolio Value')

    # Panel 2: Relative Strength
    ax2 = fig.add_subplot(gs[1, 0])
    if benchmark_series is not None:
        ba = benchmark_series.reindex(equity.index).ffill()
        rs = (equity / equity.iloc[0]) / (ba / ba.iloc[0])
        ax2.plot(rs.index, rs, color='purple', linewidth=1.2)
        ax2.set_title('2. Relative Strength vs Benchmark', fontsize=12, fontweight='bold')
        ax2.grid(True, linestyle='--', alpha=0.3)
        ax2.set_ylabel('Ratio')
    else:
        ax2.text(0.5, 0.5, 'No Benchmark', ha='center', va='center')

    # Panel 3: Active Positions
    ax3 = fig.add_subplot(gs[1, 1])
    if executed_weights is not None:
        pos_count = (executed_weights > 1e-6).sum(axis=1)
    else:
        pos_count = pd.Series(0, index=equity.index)
    ax3.fill_between(pos_count.index, pos_count, step='post', color='#9467bd', alpha=0.5)
    ax3.plot(pos_count.index, pos_count, color='#9467bd', linewidth=0.8, drawstyle='steps-post')
    ax3.set_title('3. Active Positions (Daily Count)', fontsize=12, fontweight='bold')
    ax3.grid(True, axis='y', linestyle='--', alpha=0.3)
    ax3.set_ylabel('Count')

    # Panel 4: Drawdown
    ax4 = fig.add_subplot(gs[2, :])
    ax4.fill_between(dd.index, dd, 0, color='#d62728', alpha=0.3)
    ax4.plot(dd.index, dd, color='#d62728', linewidth=1)
    ax4.set_title('4. Drawdown Profile', fontsize=12, fontweight='bold')
    ax4.grid(True, linestyle='--', alpha=0.3)
    ax4.set_ylabel('Drawdown')

    # Panel 5: Monthly Return Distribution
    ax5 = fig.add_subplot(gs[3, :])
    monthly_ret = equity.resample('ME').last().pct_change().dropna()
    ax5.hist(monthly_ret * 100, bins=50, color='teal', edgecolor='black', alpha=0.7)
    ax5.axvline(0, color='black', linestyle='--', linewidth=1)
    mean_ret = monthly_ret.mean() * 100
    ax5.axvline(mean_ret, color='blue', linestyle=':', label=f'Mean: {mean_ret:.2f}%')
    ax5.set_title('5. Monthly Return Distribution', fontsize=12, fontweight='bold')
    ax5.set_xlabel('Monthly Return (%)')
    ax5.legend()
    ax5.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(_out(f'{PREFIX}_performance.png'), dpi=150)
    plt.close(fig)
    print(f"[Graphics] Saved  →  {_out(f'{PREFIX}_performance.png')}")

    # Heatmap
    try:
        hm_df              = pd.DataFrame({'Return': monthly_ret})
        hm_df['Year']      = hm_df.index.year
        hm_df['Month']     = hm_df.index.month
        heatmap_data       = hm_df.pivot(index='Year', columns='Month', values='Return')
        plt.figure(figsize=(14, max(6, len(heatmap_data) * 0.55)))
        sns.heatmap(heatmap_data * 100, annot=True, fmt='.1f',
                    cmap='RdYlGn', center=0, cbar=False)
        plt.title(LABEL + ' — Monthly Returns Heatmap (%)', fontsize=14, fontweight='bold')
        plt.tight_layout()
        plt.savefig(_out(f'{PREFIX}_heatmap.png'), dpi=150)
        plt.close()
        print(f"[Graphics] Saved  →  {_out(f'{PREFIX}_heatmap.png')}")
    except Exception as e:
        print(f"[Graphics] Heatmap failed: {e}")


def compute_drawdown_stats(dd_series):
    """Episode-based drawdown stats: an episode is one contiguous run below a prior equity high; Avg DD (mean of each episode's own trough) separates one bad stretch from routine pain that MaxDD alone can't show."""
    underwater = dd_series < -1e-12
    episode_id = (~underwater).cumsum().where(underwater)
    if episode_id.notna().sum() == 0:
        return {'avg_drawdown': 0.0, 'avg_drawdown_underwater': 0.0, 'n_episodes': 0}
    episode_depths = dd_series.groupby(episode_id).min()
    return {
        'avg_drawdown':            float(episode_depths.mean()),
        'avg_drawdown_underwater': float(dd_series[underwater].mean()),
        'n_episodes':              int(episode_depths.shape[0]),
    }


def print_yearly_returns(portfolio_value, dd_series=None):
    yearly = portfolio_value.resample('YE').last().pct_change()
    print("\n" + "=" * 48)
    print("  Yearly Returns" + ("  +  Drawdown" if dd_series is not None else ""))
    print("=" * 48)
    if dd_series is not None:
        print(f"{'Year':<6} | {'Return':>8} | {'Yr MaxDD':>9} | {'Yr AvgDD':>9}")
    else:
        print(f"{'Year':<6} | {'Return':>8}")
    print("-" * 48)
    for dt, ret in yearly.items():
        if pd.isna(ret):
            continue
        if dd_series is not None:
            _yr_dd = dd_series[dd_series.index.year == dt.year]
            _yr_max = _yr_dd.min() if len(_yr_dd) else np.nan
            _underwater = _yr_dd[_yr_dd < -1e-12]
            _yr_avg = _underwater.mean() if len(_underwater) else 0.0
            print(f"{dt.year:<6} | {ret*100:>7.2f}% | {_yr_max*100:>8.2f}% | {_yr_avg*100:>8.2f}%")
        else:
            print(f"{dt.year:<6} | {ret*100:>7.2f}%")
    print("=" * 48)
    if dd_series is not None:
        print("  (Yr MaxDD: worst drawdown-from-all-time-peak TOUCHED during the")
        print("   year, not reset each Jan 1. Yr AvgDD: mean depth on days the")
        print("   year was actually underwater -- 0.00% means it stayed at highs.)")


def slice_results(res, start_date, risk_free_rate=0.06):
    """Trim results to the reporting window and recompute all metrics so the report reflects only the declared period."""
    eq = res['equity_curve']

    if start_date not in eq.index:
        idx = eq.index.searchsorted(start_date)
        if idx >= len(eq):
            print(f"WARNING: start_date {start_date} is after data end — not slicing.")
            return res
        start_date = eq.index[idx]

    res['equity_curve']     = eq.loc[start_date:]
    res['equity_curve']     = res['equity_curve'] / res['equity_curve'].iloc[0] * 100_000
    res['portfolio_value']  = res['equity_curve']
    res['net_returns']      = res['net_returns'].loc[start_date:]
    res['executed_weights'] = res['executed_weights'].loc[start_date:]
    for _k in ('turnover', 'vol_scale', 'corr_scale', 'regime', 'n_cooldown_tickers'):
        if _k in res:
            res[_k] = res[_k].loc[start_date:]

    eq  = res['equity_curve']
    ret = res['net_returns']

    n_years   = (eq.index[-1] - eq.index[0]).days / 365.25
    daily_rfr = (1 + risk_free_rate) ** (1 / 252) - 1

    res['cagr']          = (eq.iloc[-1] / eq.iloc[0]) ** (1 / n_years) - 1 if n_years > 0 else 0
    res['total_return']  = eq.iloc[-1] / eq.iloc[0] - 1
    res['ann_volatility'] = ret.std() * np.sqrt(252)

    excess               = ret - daily_rfr
    res['sharpe']        = (np.sqrt(252) * excess.mean() / ret.std()
                            if ret.std() != 0 else 0)

    _dn                  = ret.clip(upper=0.0)
    _dndev               = np.sqrt((_dn ** 2).mean())
    res['sortino']       = (np.sqrt(252) * ret.mean() / _dndev if _dndev > 0 else 0)

    running_max          = eq.cummax()
    dd_series            = (eq / running_max) - 1
    res['dd_series']     = dd_series
    res['max_drawdown']  = dd_series.min()
    res['calmar']        = (res['cagr'] / abs(res['max_drawdown'])
                            if res['max_drawdown'] != 0 else 0)
    res.update(compute_drawdown_stats(dd_series))

    monthly_res          = res['portfolio_value'].resample('ME').last().pct_change()
    res['win_rate']      = (monthly_res.dropna() > 0).mean()

    if 'turnover' in res and n_years > 0:
        res['ann_turnover'] = res['turnover'].sum() / n_years

    res['daily_win_rate'] = (ret > 0).mean()

    # Trade-basis placeholders (populated in main() after detailed log)
    for _k in ('trade_win_rate', 'total_trades_count', 'avg_trade_return',
               'avg_win_pct', 'avg_loss_pct', 'payoff_ratio', 'avg_holding_days',
               'avg_trading_days_held', 'best_trade', 'worst_trade',
               'profit_factor', 'profit_factor_dollar', 'median_trade_return',
               'avg_stop_pct', 'avg_mae', 'avg_mfe'):
        res[_k] = 0.0

    # ── Daily portfolio log ────────────────────────────────────────────
    log = pd.DataFrame(index=eq.index)
    log['Portfolio_Value'] = res['portfolio_value']
    log['Net_Return']      = ret
    w = res['executed_weights']
    log['Positions']       = (w > 1e-6).sum(axis=1)
    log['Exposure']        = w.sum(axis=1)
    log['Drawdown']        = dd_series
    for _k, _col in (('vol_scale', 'Vol_Scale'), ('corr_scale', 'Corr_Scale'),
                     ('regime', 'Regime'), ('n_cooldown_tickers', 'N_Cooldown_Tickers')):
        if _k in res:
            log[_col] = res[_k].reindex(log.index)
    log.to_csv(_out(f'{PREFIX}_daily_log.csv'))
    print(f"[Logs] {_out(f'{PREFIX}_daily_log.csv')}  ({len(log)} rows)")

    return res



def print_report(results, detailed_log, report_start, end_load, BACKTEST_MODE='event_driven'):
    # ── 8. Trade-basis metrics from the filtered log ──────────────────────────
    if not detailed_log.empty:
        dl      = detailed_log
        wins    = (dl['PnL_Pct'] > 0).sum()
        losses  = (dl['PnL_Pct'] < 0).sum()
        total_t = len(dl)

        results['trade_win_rate']        = wins / total_t if total_t > 0 else 0.0
        results['total_trades_count']    = total_t
        results['avg_trade_return']      = dl['PnL_Pct'].mean()
        results['median_trade_return']   = dl['PnL_Pct'].median()
        results['avg_holding_days']      = dl['Holding_Days'].mean()
        results['avg_trading_days_held'] = dl['Trading_Days_Held'].mean()
        results['best_trade']            = dl['PnL_Pct'].max()
        results['worst_trade']           = dl['PnL_Pct'].min()
        results['avg_stop_pct']          = dl['Stop_Pct'].mean()
        results['avg_mae']               = dl['MAE_Pct'].mean()
        results['avg_mfe']               = dl['MFE_Pct'].mean()

        avg_win  = dl.loc[dl['PnL_Pct'] > 0, 'PnL_Pct'].mean() if wins   > 0 else 0.0
        avg_loss = dl.loc[dl['PnL_Pct'] < 0, 'PnL_Pct'].abs().mean() if losses > 0 else 0.0
        results['avg_win_pct']  = avg_win
        results['avg_loss_pct'] = avg_loss
        results['payoff_ratio'] = avg_win / avg_loss if avg_loss > 0 else float('inf')

        gw_pct = dl.loc[dl['PnL_Pct'] > 0, 'PnL_Pct'].sum()
        gl_pct = dl.loc[dl['PnL_Pct'] < 0, 'PnL_Pct'].abs().sum()
        results['profit_factor'] = gw_pct / gl_pct if gl_pct > 0 else float('inf')

        gw_abs = dl.loc[dl['PnL_Abs'] > 0, 'PnL_Abs'].sum()
        gl_abs = dl.loc[dl['PnL_Abs'] < 0, 'PnL_Abs'].abs().sum()
        results['profit_factor_dollar'] = gw_abs / gl_abs if gl_abs > 0 else float('inf')

    # ── 9. Performance Report ─────────────────────────────────────────────────
    W = 38
    SEP = "=" * W

    print(f"\n{SEP}")
    print(f"  {LABEL}  —  PERFORMANCE REPORT")
    print(f"  ({report_start} → {end_load}, mode={BACKTEST_MODE})")
    print(SEP)

    print(f"\n── Portfolio Metrics ─────────────────")
    print(f"  CAGR              : {results['cagr']*100:>8.2f}%")
    print(f"  Total Return      : {results['total_return']*100:>8.2f}%")
    print(f"  Ann Volatility    : {results['ann_volatility']*100:>8.2f}%")
    print(f"  Max Drawdown      : {results['max_drawdown']*100:>8.2f}%")
    print(f"  Avg Drawdown      : {results.get('avg_drawdown', 0)*100:>8.2f}%"
          f"  ({results.get('n_episodes', 0)} episodes; mean of each episode's own trough)")
    print(f"  Avg DD (underwater): {results.get('avg_drawdown_underwater', 0)*100:>7.2f}%"
          f"  (mean depth on days actually below the running peak)")
    print(f"  Sharpe Ratio      : {results['sharpe']:>9.3f}")
    print(f"  Sortino Ratio     : {results['sortino']:>9.3f}")
    print(f"  Calmar Ratio      : {results['calmar']:>9.3f}")
    print(f"  Final Portfolio   : ₹{results['portfolio_value'].iloc[-1]:>12,.2f}")

    print(f"\n── Win Rate (3 views) ────────────────")
    print(f"  Daily Win Rate    : {results['daily_win_rate']*100:>8.2f}%")
    print(f"  Monthly Win Rate  : {results['win_rate']*100:>8.2f}%")
    if results['total_trades_count'] > 0:
        print(f"  Trade Win Rate    : {results['trade_win_rate']*100:>8.2f}%"
              f"  ({results['total_trades_count']} trades)")
    else:
        print(f"  Trade Win Rate    : {'N/A':>8}")

    print(f"\n── Trade Statistics ──────────────────")
    if results['total_trades_count'] > 0:
        print(f"  Total Trades      : {results['total_trades_count']:>8}")
        print(f"  Avg Trade Return  : {results['avg_trade_return']:>8.2f}%")
        print(f"  Median Trade Ret  : {results['median_trade_return']:>8.2f}%")
        print(f"  Best Trade        : {results['best_trade']:>8.2f}%")
        print(f"  Worst Trade       : {results['worst_trade']:>8.2f}%")
        print(f"  Avg Win  (trade)  : {results['avg_win_pct']:>8.2f}%")
        print(f"  Avg Loss (trade)  : -{results['avg_loss_pct']:>7.2f}%")
        print(f"  Payoff Ratio      : {results['payoff_ratio']:>9.3f}  (avg win / avg loss)")
        print(f"  Profit Factor (%) : {results['profit_factor']:>9.3f}  (equal-weighted)")
        print(f"  Profit Factor (₹) : {results['profit_factor_dollar']:>9.3f}  (rupee-weighted)")
        print(f"  Avg Holding Days  : {results['avg_holding_days']:>8.1f}  (calendar)")
        print(f"  Avg Trading Days  : {results['avg_trading_days_held']:>8.1f}  (exchange sessions)")
        print(f"  Avg Stop Pct      : {results.get('avg_stop_pct', 0):>8.2f}%  (initial ATR stop at entry)")
        print(f"  Avg MAE           : {results.get('avg_mae', 0):>8.2f}%  (max adverse excursion)")
        print(f"  Avg MFE           : {results.get('avg_mfe', 0):>8.2f}%  (max favorable excursion)")
    else:
        print("  No completed trades in reporting period.")

    if not detailed_log.empty:
        print(f"\n── Exit Breakdown (Reason → Detail) ──")
        _br = (detailed_log.groupby(['Exit_Reason', 'Exit_Detail'])
               .agg(N=('PnL_Pct', 'size'), AvgPnL=('PnL_Pct', 'mean'))
               .round(2))
        print(_br.to_string())

        print(f"\n── Entry Reason Breakdown ────────────")
        _er = (detailed_log.groupby('Entry_Reason')
               .agg(N=('PnL_Pct', 'size'),
                    AvgPnL=('PnL_Pct', 'mean'),
                    WinRate=('PnL_Pct', lambda s: (s > 0).mean() * 100))
               .round(2))
        print(_er.to_string())

        print(f"\n── Regime At Entry Breakdown ─────────")
        _rr = (detailed_log.groupby('Regime_At_Entry')
               .agg(N=('PnL_Pct', 'size'), AvgPnL=('PnL_Pct', 'mean'))
               .round(2))
        print(_rr.to_string())

    print(f"\n── Turnover ──────────────────────────")
    if 'ann_turnover' in results:
        print(f"  Ann Turnover      : {results['ann_turnover']*100:>8.2f}%  (daily weight changes × txn cost)")
    if 'ann_signal_turnover' in results:
        print(f"  Signal Turnover   : {results['ann_signal_turnover']:>8.1f}  round-trips/year (monthly rebal only)")

